### ISSUE TITLE
Arduino-Clock is synchronised to wrong In-Game clock

### ISSUE THREAD

**Issue by Xasin** [JBoye/HACKTANE#3] opened 2017-04-30 23:18 UTC
Something that is thoroughly prevening this mod from being really awesome and enjoyable is that the times that are being sent to the Arduino run with the In-Game *real time* clock, not, in fact, the bomb clock! 

This is the only issue that should be fixed soon enough, as it makes only the hit counter available for use, which is a bit sad.
((Also, maybe send out a initial timer setup, otherwise the last digits of the clock take a while to update.))

@JBoye, I hope these fixes will not take up too much time.
The mod is awesome, and I would love to use it myself - but right now that sadly won't work in all its glory.

**Comment by silvapacita** [comment] 2017-09-17 09:35
I'm having this exact problem... I saw on YouTube someone that had this problem and fixed it, anyone knows how to do it?

**Comment by silvapacita** [comment] 2017-09-17 11:00
For someone who can understand what the problem is, attached is the c# code for the arduino connector and the Hue connector. If someone correct the mod, please share with us. 
ps: i think that the arduino connector is showing on line 55 the system time instead of the bombInfo.GetTime
ps2: if you can add some lights from the arduino, please do it! :D Thank You


[Hacktane connector mods.zip](https://github.com/JBoye/HACKTANE/files/1309015/Hacktane.connector.mods.zip)

**Comment by Xasin** [comment] 2017-09-25 17:25
Even if someone were to fix this piece of code, he'd still have to submit it to the steam workshop, which only the author can do.
Sure, re-uploading the code would work, but then that might be a bit annoying for the original author (since it's basically a copy of his work)

Ultimately, @JBoye has to do something about it.

**Comment by silvapacita** [comment] 2017-09-25 17:30
Unfortunately for us, looks like @JBoye has abandoned this work of his, leaving us without any lights (no pun intended) on how to fix this problem... It's like giving a giant piece of candy to a child, but don't take the plastic off, and don't show him how to do it...

**Comment by JBoye** [comment] 2017-09-25 17:46
Hi guys. Nice to see people are interested in my mod, and sorry I didn’t get back to you sooner. 
My MacBook was not able to play KTaNE in VR after an update, so I lost interest in the project. 
However, I have now bought a nice new PC, so I’ll look into getting this up to date, and fixing this silly bug

**Comment by JBoye** [comment] 2017-09-25 20:49
@Xasin and @silvapacita can you try the new version?

I fixed the basic issue (showing the alarm clock instead of bomb timer), but I still need to make it more configurable. Its currently hardcoded to connect to the first available COM port which might not be very usefull

**Comment by silvapacita** [comment] 2017-09-26 09:03
Hi @JBoye nice to see your back! :D the clock sync problem is now ok, syncs to the correct clock. But now the beep (arduino 13 pin) small beeps on 1-2-3-4-5-6-7-8, but on the last 3 seconds of each 10, it long beeps (like if it was a strike). After you correct this problem, it would help a lot of people if you continue your plan to add the commands for lights on/off/alarm to the serial (90,91,92), so that we can add relays to our arduinos (for those who don't have Hue). Sorry for the requests, i know that you may have other priorities, but it would make the game a lot more "interactive" with the outside world, and thus, more interesting to play :)
By the way, thank you for continuing your mod, in my sincere opinion, the best one for this game!

**Comment by JBoye** [comment] 2017-09-26 09:15
Cool. I'll close this issue then, but feel free to request other features in a new issue.

Also, please create a new issue for the beeping issue.

I will try to do the Lights on/off as mentioned in #1

**Closed as completed by JBoye** 2017-09-26 09:15 UTC

**Comment by Xasin** [comment] 2017-09-26 12:30
Thanks @JBoye! 
I recently installed a DIY RGB light strip, and I think I could use a NodeMCU on my PC instead of an Arduino to control the room light via MQTT that way.

It'll look awesome!

**Comment by JBoye** [comment] 2017-09-26 13:47
Cool! Please share pictures or videos of your projects. I would love to see them. Same for you @silvapacita 👍

**Comment by silvapacita** [comment] 2017-09-27 21:23
@Xasin @JBoye Working now with new arduino code:
https://www.youtube.com/watch?v=tzdTqyKwh5I
Hopefully, it might do even more after new commands ;)
